<?php

/**
 * @file
 * Pig latin demo module.
 *
 */


/**
 * Implements hook_menu().
 * Drupal menus allow urls to be used as function calls, giving Drupal gets much
 * of its power and flexibillty.
 * See https://api.drupal.org/api/drupal/modules!system!system.api.php/function/hook_menu/7
 */
function islandora_solution_pack_biological_entity_menu() {
  return array(
    'admin/islandora/biological_entity' => array(
      'title' => 'Biological Entity Module',
      'description' => 'Configure the Biological Entity solution pack.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('solution_pack_biological_entity_admin'),
      'file' => 'includes/solution_pack_biological_entity.admin.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}
/**
 * Implements hook_theme().
 *
 * We supply a pattern so we can overide templates at the theme level if needed.
 * we can append a pid to a template and the new template file will be called
 * (the pids colon should be replaced with a dash)
 */

function islandora_solution_pack_biological_entity_theme($existing, $type, $theme, $path) {

  return array(
    'be_rank' => array(
      'template' => 'theme/islandora-rank',
      'pattern' => 'be_rank__',
      'variables' => array('islandora_object' => NULL),
    ),
    'be_taxa' => array(
      'template' => 'theme/islandora-taxa',
      'pattern' => 'be_taxa__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_preprocess_theme().
 * This is a Drupal hook, not supplied by islandora.
 * Variables required for display are assembled here and passed to the template file
 * defined in the theme function.  The function defines islandora-porcus, which
 * expands to islandora-porcus.tpl.php.
 * The isandora object has been added to the $variables array by 
 * hook_CMODEL_PID_islandora_view_object(), whihc in this case is
 * solution_pack_biological_entity_solution_pack_biological_entityCModel_islandora_view_object
 * 
 */
function islandora_solution_pack_biological_entity_preprocess_be_rank(array &$variables) {

  module_load_include('inc', 'islandora', 'includes/datastream');
  module_load_include('inc', 'islandora', 'includes/utilities');
  module_load_include('inc', 'islandora', 'includes/metadata');

  $islandora_object = $variables['islandora_object'];
  $results = $islandora_object->relationships->get('http://aims.fao.org/aos/v1.0/', 'isTaxonomicLevelOf');
  $related_taxa = array();
  foreach ($results as $child){
        $PIDhastaxalev = $child['object']['value'];
        $hastaxalev = islandora_object_load($PIDhastaxalev);
        $dc = $hastaxalev['DC']->content;
        $dc_object = DublinCore::importFromXMLString($dc);
        $related_taxa[$child['object']['value']]['title'] = $dc_object->dc['dc:title'][0];
  }
  $variables['related_taxa'] = $related_taxa;
}

function islandora_solution_pack_biological_entity_preprocess_be_taxa(array &$variables) {

  module_load_include('inc', 'islandora', 'includes/datastream');
  module_load_include('inc', 'islandora', 'includes/utilities');
  module_load_include('inc', 'islandora', 'includes/metadata');

  $islandora_object = $variables['islandora_object'];

  $results = $islandora_object->relationships->get('http://aims.fao.org/aos/v1.0/', 'hasTaxonomicLevel');
  $related_rank = array();
  foreach ($results as $child){
        $PID = $child['object']['value'];
        $fobject = islandora_object_load($PID);
        $dc = $fobject['DC']->content;
        $dc_object = DublinCore::importFromXMLString($dc);
        $related_rank[$child['object']['value']]['title'] = $dc_object->dc['dc:title'][0];
  }
  $variables['related_rank'] = $related_rank;

  $results = $islandora_object->relationships->get('http://aims.fao.org/aos/v1.0/', 'hasBroaderSynonym');
  $related_broader = array();
  foreach ($results as $child){
        $PID = $child['object']['value'];
        $fobject = islandora_object_load($PID);
        $dc = $fobject['DC']->content;
        $dc_object = DublinCore::importFromXMLString($dc);
        $related_broader[$child['object']['value']]['title'] = $dc_object->dc['dc:title'][0];
  }
  $variables['related_broader'] = $related_broader;

  $results = $islandora_object->relationships->get('http://aims.fao.org/aos/v1.0/', 'hasNarrowerSynonym');
  $related_narrower = array();
  foreach ($results as $child){
        $PID = $child['object']['value'];
        $fobject = islandora_object_load($PID);
        $dc = $fobject['DC']->content;
        $dc_object = DublinCore::importFromXMLString($dc);
        $related_narrower[$child['object']['value']]['title'] = $dc_object->dc['dc:title'][0];
  }
  $variables['related_narrower'] = $related_narrower;


}



/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 * If an object's behavior is defined by the solution_pack_biological_entity_solution_pack_biological_entityCModel content model
 * this hook takes the object being displayed and sends it to the theme function described by solution_pack_biological_entity_theme.
 * A reference to the islandora object being displayed is added here as a member of
 * the array whihc makes the seond argument to the theme function.
 */
function islandora_solution_pack_biological_entity_islandora_sp_biological_entity_rank_cmodel_islandora_view_object($object, $page_number, $page_size) {

  $output = theme('be_rank', array('islandora_object' => $object));
//  $output='RANK object';
  return array('' => $output);
}

function islandora_solution_pack_biological_entity_islandora_sp_biological_entity_taxa_cmodel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('be_taxa', array('islandora_object' => $object));
//  $output='TAXA object';
  return array('' => $output);
}

function islandora_solution_pack_biological_entity_islandora_sp_biological_entity_isolate_cmodel_islandora_view_object($object, $page_number, $page_size) {
//  $output = theme('solution_pack_biological_entity', array('islandora_object' => $object));
  $output='ISOLATE object';
  return array('' => $output);
}


/**
 * Implements hook_islandora_ingest_steps().
 * This hook adds a single ingest step, but more could be added as seperate entries.

function solution_pack_biological_entity_solution_pack_biological_entityCModel_islandora_ingest_steps(array $configuration) {
  return array(
    'solution_pack_biological_entity_file_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'solution_pack_biological_entity_upload_form',
      'module' => 'solution_pack_biological_entity',
      'file' => 'includes/solution_pack_biological_entity_upload.form.inc'
    )
  );
}
 */
/**
 * Implements hook_CMODEL_PID_islandora_object_ingested().
 * This hook tells Islandora what to do with the object once it has been ingested.
 * In this case the raw text has been uploaded so we'll be in a position to 
 * use that as input for our derived datastreams. The function
 * solution_pack_biological_entity_create_all_derivatives will be called with a refrence to the 
 * as yet uningested object. 

function solution_pack_biological_entity_solution_pack_biological_entityCModel_islandora_object_ingested($object) {
  module_load_include('inc', 'solution_pack_biological_entity', 'includes/derivatives');
  solution_pack_biological_entity_create_all_derivatives($object);
}
 */
/**
 * Implements hook_islandora_xml_form_builder_forms().
 * This hook makes a predefined ingest form for ingest.
 */

function islandora_solution_pack_biological_entity_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_solution_pack_biological_entity');
  return array(
    'BE Rank DwC' => array(
      'form_file' => "$module_path/xml/biological_entity_rank_form_dwc.xml",
    ),
    'BE Taxa DwC' => array(
      'form_file' => "$module_path/xml//biological_entity_taxa_form_dwc.xml",
    ),
  );
}
/**
 * Implements hook_islandora_content_model_forms_form_associations().
 * This hook associated our form with our content model.  Any time we try to ingest
 * an object with the islandora:porcusCModel content model, we will see this form
 * allowing us to supply relevant metadata.
 */

function islandora_solution_pack_biological_entity_islandora_content_model_forms_form_associations() {
  return array(
    'islandora_solution_pack_biological_entity_rank_dwc_form' => array(
      'content_model' => 'islandora:sp_biological_entity_rank_cmodel',
      'form_name' => 'BE Rank DwC',
      'dsid' => 'DWC',
      'title_field' => array('SimpleDarwinRecord', 'dwc_fields_taxon', 'scientificName'),
      'transform' => 'dwc_to_dc.xsl',
      'template' => FALSE,
    ),
    'islandora_solution_pack_biological_entity_taxa_dwc_form' => array(
      'content_model' => 'islandora:sp_biological_entity_taxa_cmodel',
      'form_name' => 'BE Taxa DwC',
      'dsid' => 'DWC',
      'title_field' => array('SimpleDarwinRecord', 'dwc_fields_taxon', 'scientificName'),
      'transform' => 'dwc_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}
/**
 * Implements hook_islandora_required_objects().
 * This hook ingests a very basic content model.  It is run when the module is
 * first installed.
 */
function islandora_solution_pack_biological_entity_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_solution_pack_biological_entity');
		
/** RANK CModel */	
  $solution_pack_biological_entity_rank_content_model = $connection->repository->constructObject('islandora:sp_biological_entity_rank_cmodel');
  $solution_pack_biological_entity_rank_content_model->owner = 'fedoraAdmin';
  $solution_pack_biological_entity_rank_content_model->label = 'Islandora Biological Entity Rank Content Model';
  $solution_pack_biological_entity_rank_content_model->models = 'fedora-system:ContentModel-3.0';
  
  $datastream = $solution_pack_biological_entity_rank_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_biological_entity_rank_ds_composite_model.xml", FALSE);
  $solution_pack_biological_entity_rank_content_model->ingestDatastream($datastream);

/** TAXA CModel */
  $solution_pack_biological_entity_taxa_content_model = $connection->repository->constructObject('islandora:sp_biological_entity_taxa_cmodel');
  $solution_pack_biological_entity_taxa_content_model->owner = 'fedoraAdmin';
  $solution_pack_biological_entity_taxa_content_model->label = 'Islandora Biological Entity Taxa Content Model';
  $solution_pack_biological_entity_taxa_content_model->models = 'fedora-system:ContentModel-3.0';
  
  $datastream = $solution_pack_biological_entity_taxa_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_biological_entity_taxa_ds_composite_model.xml", FALSE);
  $solution_pack_biological_entity_taxa_content_model->ingestDatastream($datastream);

/** SAMPLE CModel */    
  $solution_pack_biological_entity_sample_content_model = $connection->repository->constructObject('islandora:sp_biological_entity_sample_cmodel');
  $solution_pack_biological_entity_sample_content_model->owner = 'fedoraAdmin';
  $solution_pack_biological_entity_sample_content_model->label = 'Islandora Biological Entity Sample Content Model';
  $solution_pack_biological_entity_sample_content_model->models = 'fedora-system:ContentModel-3.0';
  
  $datastream = $solution_pack_biological_entity_sample_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_biological_entity_sample_ds_composite_model.xml", FALSE);
  $solution_pack_biological_entity_sample_content_model->ingestDatastream($datastream);

  /** ISOLATE CModel */    
  $solution_pack_biological_entity_isolate_content_model = $connection->repository->constructObject('islandora:sp_biological_entity_isolate_cmodel');
  $solution_pack_biological_entity_isolate_content_model->owner = 'fedoraAdmin';
  $solution_pack_biological_entity_isolate_content_model->label = 'Islandora Biological Entity Isolate Content Model';
  $solution_pack_biological_entity_isolate_content_model->models = 'fedora-system:ContentModel-3.0';
  
  $datastream = $solution_pack_biological_entity_isolate_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_biological_entity_isolate_ds_composite_model.xml", FALSE);
  $solution_pack_biological_entity_isolate_content_model->ingestDatastream($datastream);
  
/** RANK root collection */  
  $rank_collection = $connection->repository->constructObject('islandora:rank_collection');
  $rank_collection->owner = 'fedoraAdmin';
  $rank_collection->label = 'Taxonomic levels';
  $rank_collection->models = 'islandora:collectionCModel';
  $rank_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');

  $datastream = $rank_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_biological_entity_rank_collection_policy.xml", FALSE);
  $rank_collection->ingestDatastream($datastream);

  $datastream = $rank_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $rank_collection->ingestDatastream($datastream);

/** TAXA root collection */
  $taxa_collection = $connection->repository->constructObject('islandora:taxa_collection');
  $taxa_collection->owner = 'fedoraAdmin';
  $taxa_collection->label = 'Taxonomy';
  $taxa_collection->models = 'islandora:collectionCModel';
  $taxa_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');

  $datastream = $taxa_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_biological_entity_taxa_collection_policy.xml", FALSE);
  $taxa_collection->ingestDatastream($datastream);

  $datastream = $taxa_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $taxa_collection->ingestDatastream($datastream);

/** SAMPLE root collection */
  $sample_collection = $connection->repository->constructObject('islandora:sample_collection');
  $sample_collection->owner = 'fedoraAdmin';
  $sample_collection->label = 'Samples';
  $sample_collection->models = 'islandora:collectionCModel';
  $sample_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');

  $datastream = $sample_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_biological_entity_sample_collection_policy.xml", FALSE);
  $sample_collection->ingestDatastream($datastream);

  $datastream = $sample_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $sample_collection->ingestDatastream($datastream);

/** ISOLATE root collection */
  $isolate_collection = $connection->repository->constructObject('islandora:isolate_collection');
  $isolate_collection->owner = 'fedoraAdmin';
  $isolate_collection->label = 'Isolates';
  $isolate_collection->models = 'islandora:collectionCModel';
  $isolate_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');

  $datastream = $isolate_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_biological_entity_isolate_collection_policy.xml", FALSE);
  $isolate_collection->ingestDatastream($datastream);

  $datastream = $isolate_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $isolate_collection->ingestDatastream($datastream);
  
  return array(
    'islandora_solution_pack_biological_entity' => array(
      'title' => 'Islandora Biological Entity',
      'objects' => array(
        $solution_pack_biological_entity_rank_content_model,
        $solution_pack_biological_entity_taxa_content_model,
        $solution_pack_biological_entity_sample_content_model,
        $solution_pack_biological_entity_isolate_content_model,
        $rank_collection,
        $taxa_collection,
        $sample_collection,
        $isolate_collection,
      ),
    ),
  );
}
