<?php

/**
 * @file
 *
 * Installs the required object for solution pack.
 */

/**
 * Implements hook_install().
 *
 * @see islandora_islandora_required_objects()
 */
function islandora_solution_pack_biological_entity_install() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('islandora_solution_pack_biological_entity');
}

/**
 * Implementation of hook_uninstall.
 */
function islandora_solution_pack_biological_entity_uninstall() {

}
